Repository GSG-G9/house-hunting-app, pull requests merged in 2021-02, with the labels that each got.

#47 add live demo and team section to read me file
  README.md
Labels: done

#43 install eslint package and initialize it
  .eslintrc.json
  .travis.yml
  client/.eslintcache
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/index.js
  package-lock.json
  package.json
Labels: config, done

#51 edit eslint and travis config
  .eslintrc.json
  .travis.yml
  __test__/queries/user.test.js
  __test__/routes/users.test.js
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
Labels: awaiting-review

#56 fix error jest version
  .vscode/setting.json
  .vscode/settings.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/index.js
  package-lock.json
  package.json
Labels: config, done

#49 connection and build between database and server
  .gitignore
  __test__/queries/user.test.js
  __test__/routes/users.test.js
  client/.eslintrc.json
  client/package-lock.json
  client/src/index.js
  package-lock.json
  package.json
  server/database/config/build.js
  server/database/config/connection.js
Labels: awaiting-review, database

#54 38 setup server
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  server/app.js
  server/controller/error/404.js
  server/controller/error/500.js
  server/controller/error/index.js
  server/database/config/build.js
  server/database/config/connection.js
  server/index.js
  server/router/index.js
Labels: back-end, done

#81 80 custom theme
  client/src/App/index.js
  client/src/App/style.css
  client/src/App/theme.js
  client/src/index.css
  client/src/index.js
Labels: awaiting-review

#82 add Route path
  client/src/App/index.js
  client/src/Utils/routes.constant.js
Labels: awaiting-review

#62 Card Component structure
  .vscode/settings.json
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
  client/src/Components/Card/style.js
  client/src/Utils/images/card/house.png
Labels: awaiting-review, priority-one

#78 Create Footer Component
  client/src/Components/Footer/index.js
  client/src/Components/Footer/style.css
  client/src/Components/Footer/style.js
Labels: awaiting-review, priority-three

#79 Create LinkItem Component
  client/src/Components/LinkItem/index.js
  client/src/Components/LinkItem/style.css
  client/src/Components/LinkItem/style.js
Labels: awaiting-review

#77 Create Header Component
  client/src/Components/Button/index.js
  client/src/Components/Button/style.js
  client/src/Components/Header/index.js
  client/src/Components/Header/style.css
  client/src/Components/LinkItem/index.js
  client/src/Components/Navbar/index.js
  client/src/Components/Navbar/style.js
Labels: awaiting-review, priority-one

#73 container card component
  client/src/App/index.js
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.css
  client/src/Components/CardContainer/style.js
Labels: awaiting-review, priority-two

#84 Inputfield component
  client/package-lock.json
  client/src/Components/Input/index.js
Labels: awaiting-review, priority-one

#94 layout Page
  client/src/App/index.js
  client/src/Pages/Layout/index.js
Labels: awaiting-review, front-end, priority-one

#87 signup route
  __test__/queries/index.js
  client/src/Utils/images/card/house.png
  package-lock.json
  package.json
  server/app.js
  server/controller/error/500.js
  server/controller/routes/user/index.js
  server/controller/routes/user/signup.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/user/addUser.js
  server/database/queries/user/checkUserByEmail.js
  server/database/queries/user/index.js
  server/middleware/validation/.gitkeep
  server/middleware/validation/index.js
  server/middleware/validation/signupSchema.js
  server/router/index.js
  server/router/user.js
  server/utils/boomify.js
Labels: awaiting-review, priority-one

#89 Write logout route and logout controller
  server/controller/routes/index.js
  server/controller/routes/user/index.js
  server/controller/routes/user/logout.js
  server/router/index.js
  server/router/user.js
Labels: awaiting-review

#88 login route
  package-lock.json
  package.json
  server/app.js
  server/controller/error/404.js
  server/controller/error/500.js
  server/controller/error/index.js
  server/controller/routes/user/index.js
  server/controller/routes/user/login.js
  server/controller/routes/user/logout.js
  server/middleware/validation/index.js
  server/middleware/validation/login.js
  server/middleware/validation/signup.js
  server/router/index.js
  server/router/user.js
Labels: awaiting-review, priority-one

#90 Build getHouses process
  .gitignore
  server/controller/routes/house/getHouses.js
  server/controller/routes/house/index.js
  server/database/queries/house/getAllHousesData.js
  server/database/queries/house/index.js
  server/router/house.js
  server/router/index.js
Labels: awaiting-review

#98 sign up page
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/Components/Footer/style.js
  client/src/Pages/Layout/style.css
  client/src/Pages/Login/style.css
  client/src/Pages/Register/index.js
  client/src/Pages/Register/style.css
  client/src/Pages/Register/style.js
  client/src/Utils/images/house_searching.svg
  package-lock.json
Labels: Approved, awaiting-review

#100 Protect middleware
  server/app.js
  server/controller/routes/user/login.js
  server/middleware/auth/checkToken.js
  server/utils/jwtFunctions.js
Labels: Approved, awaiting-review

#92 Landing page
  client/src/App/index.js
  client/src/Components/Card/index.js
  client/src/Components/Card/style.js
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.js
  client/src/Components/Footer/style.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Landing/style.css
  client/src/Pages/Landing/style.js
  package-lock.json
Labels: awaiting-review

#102 get/getHouseByLocation
  server/controller/routes/house/getHouseByLocation.js
  server/controller/routes/house/index.js
  server/database/config/fakeData.sql
  server/database/queries/house/getHouseByLocation.js
  server/database/queries/house/index.js
  server/router/house.js
Labels: back-end, priority-two, request-change

#103 POST/ Add new house
  server/controller/routes/house/addNewHouse.js
  server/controller/routes/house/getHouses.js
  server/controller/routes/house/index.js
  server/database/queries/house/addNewHouse.js
  server/database/queries/house/getAllHousesData.js
  server/database/queries/house/index.js
  server/middleware/auth/index.js
  server/middleware/validation/addNewHouse.js
  server/middleware/validation/index.js
  server/router/house.js
Labels: awaiting-review, back-end, priority-one

#107 Create SideBar Component
  client/src/App/index.js
  client/src/Pages/Profile/AddHouse.js
  client/src/Pages/Profile/AddHouse/index.js
  client/src/Pages/Profile/AddHouse/staticData.js
  client/src/Pages/Profile/AddHouse/style.js
  client/src/Pages/Profile/SideBar/index.js
  client/src/Pages/Profile/SideBar/style.js
  client/src/Pages/Profile/SideBar/tabPanel.js
  client/src/Pages/Profile/index.js
  client/src/Pages/Profile/style.css
  client/src/Pages/Profile/style.js
  client/src/Utils/validations/addNewHouse.js
  server/middleware/validation/addNewHouse.js
Labels: front-end, request-change

#113 GET/ Newest Houses
  client/src/Components/Card/index.js
  client/src/Components/Card/style.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Profile/AddHouse/index.js
  client/src/Utils/staticData.js
  server/controller/routes/house/getNewestHouses.js
  server/controller/routes/house/index.js
  server/database/queries/house/getNewestHousesData.js
  server/database/queries/house/index.js
  server/router/publicRoutes.js
Labels: Approved, back-end, front-end

#119 Is Auth route
  server/controller/routes/user/index.js
  server/controller/routes/user/isAuth.js
  server/router/publicRoutes.js
Labels: awaiting-review, back-end

#109 Favorite list page
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/Components/CardContainer/index.js
  client/src/Components/Footer/style.js
  client/src/Pages/FavoriteList/columns.js
  client/src/Pages/FavoriteList/index.js
  client/src/Pages/FavoriteList/style.css
  client/src/Pages/FavoriteList/style.js
Labels: awaiting-review, front-end

#105 Search page
  client/src/App/index.js
  client/src/Components/AdvanceSearch/index.js
  client/src/Components/AdvanceSearch/style.js
  client/src/Components/CardContainer/index.js
  client/src/Components/SearchBar/index.js
  client/src/Components/SearchBar/style.js
  client/src/Pages/Houses/index.js
  client/src/Pages/Houses/style.css
  client/src/Pages/Houses/style.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Landing/style.js
  server/database/config/fakeData.sql
Labels: front-end, priority-one, request-change

#118 Get user Data
  client/src/Pages/Houses/index.js
  server/controller/routes/user/getUser.js
  server/controller/routes/user/index.js
  server/database/queries/user/getUserData.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: awaiting-review, back-end, priority-two

#124 get/Add House To Favorite List
  server/controller/routes/house/addHouseToFav.js
  server/controller/routes/house/getNewestHouses.js
  server/controller/routes/house/index.js
  server/database/queries/house/addHouseToFavList.js
  server/database/queries/house/getNewestHousesData.js
  server/database/queries/house/index.js
  server/router/house.js
Labels: awaiting-review, back-end

#121 Private routes
  client/src/App/index.js
  client/src/Components/Navbar/index.js
  client/src/Components/Route/PrivateRoute.js
  client/src/Components/Route/PublicRoute.js
  client/src/Components/Route/index.js
  client/src/Context/AuthContext.js
  client/src/Context/Authorization.js
  client/src/Pages/Login/index.js
  client/src/Pages/Profile/index.js
Labels: Adham, awaiting-review, priority-one

#115 111 house details
  client/src/App/index.js
  client/src/Components/Card/index.js
  client/src/Components/Card/style.js
  client/src/Components/CardContainer/index.js
  client/src/Pages/DetailsHouse/RelatedHouse/index.js
  client/src/Pages/DetailsHouse/RelatedHouse/style.js
  client/src/Pages/DetailsHouse/index.js
  client/src/Pages/DetailsHouse/style.css
  client/src/Pages/DetailsHouse/style.js
  client/src/Pages/Houses/index.js
  client/src/Pages/Landing/index.js
  client/src/Utils/staticData.js
  server/controller/routes/house/getHouseById.js
  server/controller/routes/house/index.js
  server/database/queries/house/getAllHousesData.js
  server/database/queries/house/getHouseByLocation.js
  server/database/queries/house/getHouseData.js
  server/database/queries/house/getNewestHousesData.js
  server/database/queries/house/index.js
  server/router/publicRoutes.js
Labels: awaiting-review

#131 fix add to favorite
  server/controller/routes/house/addHouseToFav.js
  server/database/queries/house/getHousesFromFav.js
  server/database/queries/house/index.js
Labels: awaiting-review, back-end

#128 add house to favorite on click favorite icon
  client/src/Components/Card/index.js
  client/src/Components/Card/style.js
  server/controller/routes/house/addHouseToFav.js
  server/controller/routes/house/adduserHouses.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/house/getHousesFromFav.js
  server/database/queries/house/index.js
Labels: awaiting-review, front-end, priority-one

#127 Update user info route
  server/controller/routes/user/index.js
  server/controller/routes/user/updateUser.js
  server/database/queries/user/index.js
  server/database/queries/user/updateUser.js
  server/middleware/validation/index.js
  server/middleware/validation/updateUser.js
  server/router/user.js
Labels: awaiting-review, back-end, database, priority-three

#132 user houses
  server/controller/routes/house/adduserHouses.js
  server/controller/routes/user/getUserHouses.js
  server/controller/routes/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/user/getUserHouses.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: back-end, request-change

#125 Show user information on the profile page
  client/src/Pages/Profile/AddHouse/index.js
  client/src/Pages/Profile/AddHouse/style.js
  client/src/Pages/Profile/SideBar/index.js
  client/src/Pages/Profile/SideBar/style.js
  client/src/Pages/Profile/UserInfo/index.js
  client/src/Pages/Profile/UserInfo/style.js
  client/src/Pages/Profile/style.js
Labels: front-end, priority-two, request-change

#135 33 delete favhouse
  server/controller/routes/house/deleteFavoriteHouse.js
  server/controller/routes/house/index.js
  server/database/queries/house/deleteFromFavoriteHouses.js
  server/database/queries/house/index.js
  server/router/house.js
Labels: awaiting-review, back-end

#143 Delete user-account route
  server/controller/routes/user/deleteUser.js
  server/controller/routes/user/index.js
  server/database/queries/user/deleteUser.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: Adham, awaiting-review, back-end, database

#147 Delete House
  server/controller/routes/house/deleteHouse.js
  server/controller/routes/house/index.js
  server/database/queries/house/deleteHouse.js
  server/database/queries/house/index.js
  server/router/house.js
Labels: Approved, awaiting-review, back-end, yasmeen

#137 user house page
  client/src/Pages/Profile/Houses/index.js
  client/src/Pages/Profile/Houses/style.js
  client/src/Pages/Profile/SideBar/index.js
Labels: front-end, request-change, yasmeen

#151 ContactUs AboutUs page
  client/public/image/undraw_best_place_r685.svg
  client/public/image/undraw_contact_us_15o2.svg
  client/src/App/index.js
  client/src/Pages/AboutUs/index.js
  client/src/Pages/AboutUs/style.css
  client/src/Pages/AboutUs/style.js
  client/src/Pages/ContactUs/index.js
  client/src/Pages/ContactUs/style.css
  client/src/Pages/ContactUs/style.js
Labels: Muhammed, awaiting-review, component

#153 delete house
  client/.gitignore
  client/src/Components/Table/index.js
  client/src/Components/Table/style.js
  client/src/Pages/Profile/Houses/index.js
  client/src/Pages/Profile/Houses/style.js
Labels: awaiting-review, front-end, yasmeen

#159 155 loading
  client/src/Components/Loading/index.js
  client/src/Components/Navbar/index.js
  client/src/Context/Authorization.js
  client/src/Pages/DetailsHouse/RelatedHouse/index.js
  client/src/Pages/DetailsHouse/index.js
  client/src/Pages/Houses/index.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Layout/index.js
  client/src/Pages/Layout/style.js
  client/src/Pages/Login/index.js
  client/src/Pages/Profile/AddHouse/index.js
  client/src/Pages/Profile/AddHouse/style.js
  client/src/Pages/Profile/Houses/index.js
  client/src/Pages/Profile/Houses/style.js
  client/src/Pages/Profile/UpdateUserInfo/index.js
  client/src/Pages/Profile/UpdateUserInfo/style.js
  client/src/Pages/Profile/UserInfo/index.js
  client/src/Pages/Profile/UserInfo/style.js
  client/src/Pages/Register/index.js
Labels: awaiting-review, front-end, the King

#162 Header Section
  client/public/image/hp-hero-desktop.webp
  client/src/Components/Card/index.js
  client/src/Components/Card/style.js
  client/src/Components/SearchBar/index.js
  client/src/Components/SearchBar/style.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Landing/style.js
Labels: awaiting-review, front-end

#160 fake data
  client/src/Components/Card/index.js
  server/database/config/fakeData.sql
Labels: awaiting-review, the King, yasmeen

#163 Not found page
  client/src/App/index.js
  client/src/Pages/NotFound/index.js
  client/src/Pages/NotFound/style.css
  client/src/Pages/NotFound/style.js
  client/src/Utils/images/notFound.svg
Labels: Adham, awaiting-review, front-end

#165 Add favorite house
  client/src/Components/Card/index.js
  client/src/Context/Authorization.js
  client/src/Pages/DetailsHouse/index.js
  client/src/Pages/DetailsHouse/style.js
Labels: awaiting-review

#136 133 update user info page
  client/src/Pages/Profile/UpdateUserInfo/index.js
  client/src/Pages/Profile/UpdateUserInfo/style.js
  client/src/Pages/Profile/UserInfo/ViewUserinfo/index.js
  client/src/Pages/Profile/UserInfo/index.js
  client/src/Utils/validations/updateUser.js
  server/middleware/validation/updateUser.js
Labels: front-end, in-progress

#168 fix Bugs
  client/src/Components/Footer/index.js
  client/src/Components/Footer/style.js
  server/database/config/fakeData.sql
Labels: fix-issues

#169 add fake data to the card
  client/src/Components/Card/index.js
  client/src/Pages/DetailsHouse/index.js
Labels: fix-issues

#179 edit profile houses style
  client/src/Components/Table/index.js
  client/src/Components/Table/style.js
Labels: awaiting-review, fix-issues

#180 Upload image
  package-lock.json
  package.json
  server/controller/routes/user/index.js
  server/controller/routes/user/updateUserImage.js
  server/database/queries/user/index.js
  server/database/queries/user/updateUserImageData.js
  server/router/user.js
  server/utils/cloudinary.js
Labels: awaiting-review
